### PR TITLE
Project where three nao bots dance to Staying Alive by Bee Gees

### PR DESCRIPTION
**Pull request by Milindi-Kodikara**
Please take a look at the README.md for more details :)

### CODE REVIEW

**Comment by omichel** [comment]
That is super cool, but I am wondering whether we are allowed to publish proprietary MP3 files on GitHub, do you know anything about the license of the MP3 files which don't seem to belong to you?

**Comment by Milindi-Kodikara** [comment]
> That is super cool, but I am wondering whether we are allowed to publish proprietary MP3 files on GitHub, do you know anything about the license of the MP3 files which don't seem to belong to you?

I have the video for this on YouTube as well, and as long as this is not for profit i.e involving money I think it should be okay @omichel . . . I could be wrong tho

**Comment by omichel** [comment]
Because I am not sure about MP3 files license, I would be more comfortable if you could host this simulation on your own repository, e.g., at https://github.com/Milindi-Kodikara/dancing_nao/ for example. We could link it from there if you want.

**Comment by Milindi-Kodikara** [comment]
Yup absolutely, here's the repo https://github.com/Milindi-Kodikara/Staying-Alive

**Comment by omichel** [comment]
Replaced with #18.

**Pull request closed without merging**
